CC = gcc
OBJS = main.o game.o solver.o stack.o doublyLinkedList.o board.o parser.o def.o errors.o LP.o 
EXEC = console_sudoku
COMP_FLAG = -ansi -O3 -Wall -Wextra -Werror -pedantic-errors
GUROBI_COMP = -I/usr/local/lib/gurobi563/include
GUROBI_LIB = -L/usr/local/lib/gurobi563/lib -lgurobi56

$(EXEC): $(OBJS)
	$(CC) $(OBJS) $(GUROBI_LIB) -o $@ -lm
main.o: main.c doublyLinkedList.h game.h board.h solver.h stack.h parser.h game.h def.c LP.h errors.h
	$(CC) $(COMP_FLAG) $(GUROBI_COMP) -c $*.c
game.o: game.c game.h doublyLinkedList.h board.h stack.h solver.h parser.h def.c errors.h 
	$(CC) $(COMP_FLAG) -c $*.c
parser.o: parser.c parser.h game.h
	$(CC) $(COMP_FLAG) -c $*.c
solver.o: solver.c solver.h stack.h LP.h errors.h
	$(CC) $(COMP_FLAG) $(GUROBI_COMP) -c $*.c
doublyLinkedList.o: doublyLinkedList.c doublyLinkedList.h 
	$(CC) $(COMP_FLAG) -c $*.c
def.o: def.c board.h
	$(CC) $(COMP_FLAG) -c $*.c
LP.o: LP.c LP.h board.h errors.h
	$(CC) $(COMP_FLAG) $(GUROBI_COMP) -c $*.c
errors.o: errors.c errors.h def.c  
	$(CC) $(COMP_FLAG) -c $*.c
stack.o: stack.c stack.h
	$(CC) $(COMP_FLAG) -c $*.c
board.o: board.c board.h
	$(CC) $(COMP_FLAG) -c $*.c
clean:
	rm -f $(OBJS) $(EXEC)